Adds optional flags -f -h for force publishing and help.

diff --git a/_scripts/publish b/_scripts/publish
--- a/_scripts/publish
+++ b/_scripts/publish
@@ -1,34 +1,67 @@
-#!/bin/bash -x
-#
-# Perform some checks, create a build and ssh it over to put put it into
-# production.
-#
-# Yes, it would be nicer if this worked as:
-#
-#   a) a push to production, with a post hook that would build it and place the
-#   artifacts into production requiring only a $ git push production to release
-#   the latest version.
-#
-#   b) a web hook triggering a pull and build from the web server, which would
-#   place the artifacts into production.
-#
-# Both would require the ability to build on the web server, however, which I
-# did not succeed at as of yet. Solution a would also require a running git
-# server, while b would need a web hook poller.
+#!/bin/bash
+helpf() {
+  cat <<HELP
 
-# exit if anything fails
-set -e
-set -o pipefail
+  USAGE: ${0##*/} [options]
 
+  Perform some checks, create a build and ssh it over to put put it into
+  production.
+
+  OPTIONS:
+    -h:  output help
+    -f:  skip the tests and force the publishing. Usefull when intending to
+         publish any branch other than master - which should only be done with
+         care.
+
+  NOTES:
+
+    Yes, it would be nicer if this worked as:
+
+    A)  a push to production, with a post hook that would build it and place the
+        artifacts into production requiring only a
+          $ git push production
+        to release the latest version.
+
+    B)  a web hook triggering a pull and build from the web server, which would
+        place the artifacts into production.
+
+    Both would require the ability to build on the web server, however, which I
+    did not succeed at as of yet. Solution A would also require a running git
+    server, while B would need a web hook poller.
+HELP
+exit $1
+}
+
+FORCE=false
 USER=essentials
 SERVER=applications.xebia.com
 BUILD_DIR="_site"
 PRODUCTION_DIR='static'
 
-# Ensure we're in complete synch with origin/master, as production should
-# always mirror the upstream repository
-git fetch origin master
-[[ $(git rev-parse HEAD) == $(git rev-parse origin/master) ]] || exit 1
+while getopts "hf" o; do
+  case "${o}" in
+    f)
+      FORCE=true ;;
+    h)
+      helpf ;;
+    *)
+      helpf 1 ;;
+  esac
+done
+
+# exit if anything fails
+set -e
+set -o pipefail
+
+if [ $FORCE = false ]; then
+  # Ensure we're in complete synch with origin/master, as production should
+  # always mirror the upstream repository
+  git fetch origin master >/dev/null 2>&1
+  if [[ $(git rev-parse HEAD) != $(git rev-parse origin/master) ]]; then
+    echo 'ABORTING: Not currently on origin/master. Run with -f to force publish an alternate branch or -h for help.'
+    exit 1
+  fi
+fi
 
 # Not sure if Jekyll cleans up old builds. Rm and rebuild
 rm -rf "${BUILD_DIR}"
